import { calculateRisk } from "./riskAgent.js";
import { generateReasoning } from "./reasoningAgent.js";
import { generateRoadmap } from "./roadmapAgent.js";
import { generateRecommendations } from "./recommendationAgent.js";
import { predictSuccess } from "./successPredictionAgent.js";
import { predictFutureRisk } from "./futureRiskAgent.js";
import { getInterventionPriority } from "./interventionAgent.js";
import { retrieveKnowledge } from "./knowledgeAgent.js";

export const analyzeStudent = (studentData) => {

  const riskResult =
    calculateRisk(studentData);

  const riskBreakdown = {
  attendance:
    Number(studentData.attendance) < 75
      ? 30
      : 0,

  marks:
    Number(studentData.marks) < 50
      ? 30
      : 0,

  assignments:
    Number(studentData.assignments) < 5
      ? 20
      : 0,

  gpa:
    Number(studentData.gpa) < 7
      ? 20
      : 0,
};

  const reasoning =
    generateReasoning(studentData);

  const roadmap =
    generateRoadmap(studentData);

  const recommendations =
    generateRecommendations(studentData);

  const successPrediction =
    predictSuccess(studentData);

  const futurePrediction =
    predictFutureRisk(studentData);

  const interventionPriority =
    getInterventionPriority(
      riskResult.riskLevel
    );

  const retrievedKnowledge =
    retrieveKnowledge(
      riskResult.riskLevel
    );

  const confidenceScore =
    riskResult.riskLevel === "High Risk"
      ? "92%"
      : riskResult.riskLevel === "Medium Risk"
      ? "85%"
      : "95%";

  const studentCategory =
    riskResult.riskLevel === "High Risk"
      ? "At-Risk Student"
      : riskResult.riskLevel === "Medium Risk"
      ? "Needs Monitoring"
      : "High Performer";

  const facultyActionPlan =
    riskResult.riskLevel === "High Risk"
      ? [
          "Schedule immediate mentoring session",
          "Arrange parent meeting",
          "Monitor progress weekly",
          "Provide academic support resources",
        ]
      : riskResult.riskLevel === "Medium Risk"
      ? [
          "Conduct bi-weekly review",
          "Track assignment completion",
          "Encourage participation in study groups",
        ]
      : [
          "Recognize academic excellence",
          "Provide advanced learning opportunities",
          "Encourage leadership activities",
        ];

  return {
    studentName: studentData.name,

    studentData: {
      attendance: Number(studentData.attendance),
      marks: Number(studentData.marks),
      assignments: Number(studentData.assignments),
      gpa: Number(studentData.gpa),
    },

    riskScore: riskResult.riskScore,
    riskLevel: riskResult.riskLevel,

    confidenceScore,
    studentCategory,

    reasoning,
    roadmap,
    recommendations,

    successPrediction,
    futurePrediction,

    interventionPriority,
    retrievedKnowledge,
    riskBreakdown,

    summary: {
      status:
        riskResult.riskLevel === "High Risk"
          ? "Needs Immediate Attention"
          : riskResult.riskLevel === "Medium Risk"
          ? "Monitor Progress"
          : "Performing Well",

      summary:
        "Student performance summary generated by EduScope AI.",

      outcome:
        "Following recommendations can improve academic performance.",
    },

   aiAdvice:
  riskResult.riskLevel === "High Risk"
    ? `Student is currently classified as High Risk.

Key Concerns:
• Low attendance
• Poor academic performance
• Increased dropout probability

Recommended Actions:
• Schedule mentoring sessions
• Monitor weekly progress
• Provide academic support

Expected Outcome:
• Risk reduction within 30-60 days`
    : riskResult.riskLevel === "Medium Risk"
    ? `Student is classified as Medium Risk.

Key Concerns:
• Performance inconsistency
• Need for closer monitoring

Recommended Actions:
• Track assignments
• Conduct bi-weekly reviews

Expected Outcome:
• Improvement in academic consistency`
    : `Student is performing well.

Strengths:
• Strong attendance
• Good academic performance
• Consistent progress

Recommended Actions:
• Encourage advanced learning
• Provide leadership opportunities

Expected Outcome:
• Continued academic excellence`,

    agentReasoning:
      "Coordinator Agent combined outputs from Risk, Reasoning, Roadmap, Recommendation, Success Prediction and Future Risk Agents.",

    facultyActionPlan,

    agentDecision: [
      "Risk Agent completed analysis",
      "Reasoning Agent generated insights",
      "Roadmap Agent generated action plan",
      "Recommendation Agent generated recommendations",
      "Success Prediction Agent generated probability",
      "Future Risk Agent generated forecast",
      "Intervention Agent assigned priority",
      "Knowledge Agent retrieved academic guidance",
    ],
  };
};